# Generated by Django 3.2.12 on 2024-05-04 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_patientfile_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('label', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Broken'), (2, 'Not Broken')], null=True)),
                ('zone', models.CharField(blank=True, max_length=20, null=True)),
                ('member', models.CharField(blank=True, max_length=20, null=True)),
                ('hardware', models.BooleanField(default=False)),
                ('patient_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patientfile')),
            ],
        ),
    ]
