# Generated by Django 3.2.12 on 2024-05-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reportfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record',
        ),
    ]
