# Generated by Django 3.2.12 on 2024-05-04 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_record_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportfile',
            name='zone',
        ),
    ]
