# Generated by Django 3.2.12 on 2024-05-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_reportfile_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
